version: "3"
services:
  bibuyanov-api:
    container_name: bibuyanov-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_DRIVER_CLASS_NAME=${DATABASE_DRIVER_CLASS_NAME}
      - DATABASE_URL=${DATABASE_URL}